#PBS -e out/
#PBS -o out/
#PBS -j oe
#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=1:mem=24gb
#PBS -J 1-220

cd $HOME
module load anaconda3/personal
source activate r420
cd Inferring-fungal-growth-rates-from-OD-data
IC_USED=all_ICs
FOLD_NO=$NULL
TOT_J=$(echo $PBS_JOBID | sed 's/\[[0-9]*\]//g')
echo "03b_data_idxs for $IC_USED and ${FOLD_NO:-5} folds is Job ID: $PBS_JOBID" >> log_file.$TOT_J
Rscript R/03_validate/03b_fit_model.R $IC_USED $FOLD_NO
